baseurl: "http://netlifycms-hugo-demo.aws.clement.lesne.pro/"
enableGitInfo: true

languageCode: "en-us"
title: "netlifycms-hugo-demo"
enableRobotsTXT: true
enableEmoji: true

paginate: 20
permalinks:
  post: /:year/:month/:title/
